export const data = {
  pageSize: 10,
  pageNum: 0,
  totals: 16,
  totalPages: 2,
  records: [
    {
      productId: 'USR-0001',
      name: { first: 'Olivia', last: 'Bennett' },
      email: 'olivia.bennett@example.com',
      phone: '13800138001',
      gender: 'female',
    },
    {
      productId: 'USR-0002',
      name: { first: 'Liam', last: 'Carter' },
      email: 'liam.carter@example.com',
      phone: '13800138002',
      gender: 'male',
    },
    {
      productId: 'USR-0003',
      name: { first: 'Emma', last: 'Hayes' },
      email: 'emma.hayes@example.com',
      phone: '13800138003',
      gender: 'female',
    },
    {
      productId: 'USR-0004',
      name: { first: 'Noah', last: 'Turner' },
      email: 'noah.turner@example.com',
      phone: '13800138004',
      gender: 'male',
    },
    {
      productId: 'USR-0005',
      name: { first: 'Ava', last: 'Mitchell' },
      email: 'ava.mitchell@example.com',
      phone: '13800138005',
      gender: 'female',
    },
    {
      productId: 'USR-0006',
      name: { first: 'Ethan', last: 'Reed' },
      email: 'ethan.reed@example.com',
      phone: '13800138006',
      gender: 'male',
    },
    {
      productId: 'USR-0007',
      name: { first: 'Sophia', last: 'Morris' },
      email: 'sophia.morris@example.com',
      phone: '13800138007',
      gender: 'female',
    },
    {
      productId: 'USR-0008',
      name: { first: 'Mason', last: 'Cooper' },
      email: 'mason.cooper@example.com',
      phone: '13800138008',
      gender: 'male',
    },
    {
      productId: 'USR-0009',
      name: { first: 'Isabella', last: 'Foster' },
      email: 'isabella.foster@example.com',
      phone: '13800138009',
      gender: 'female',
    },
    {
      productId: 'USR-0010',
      name: { first: 'Logan', last: 'Parker' },
      email: 'logan.parker@example.com',
      phone: '13800138010',
      gender: 'male',
    },
    {
      productId: 'USR-0011',
      name: { first: 'Mia', last: 'Brooks' },
      email: 'mia.brooks@example.com',
      phone: '13800138011',
      gender: 'female',
    },
    {
      productId: 'USR-0012',
      name: { first: 'Lucas', last: 'Ward' },
      email: 'lucas.ward@example.com',
      phone: '13800138012',
      gender: 'male',
    },
    {
      productId: 'USR-0013',
      name: { first: 'Charlotte', last: 'Price' },
      email: 'charlotte.price@example.com',
      phone: '13800138013',
      gender: 'female',
    },
    {
      productId: 'USR-0014',
      name: { first: 'James', last: 'Kelly' },
      email: 'james.kelly@example.com',
      phone: '13800138014',
      gender: 'male',
    },
    {
      productId: 'USR-0015',
      name: { first: 'Amelia', last: 'Rivera' },
      email: 'amelia.rivera@example.com',
      phone: '13800138015',
      gender: 'female',
    },
    {
      productId: 'USR-0016',
      name: { first: 'Henry', last: 'Bell' },
      email: 'henry.bell@example.com',
      phone: '13800138016',
      gender: 'male',
    },
  ],
};
