/**
 * @file src/pages/AR-Statements/ViewVoice.tsx
 * @author leon.wang
 */

import React from 'react';
import { Button, Drawer, Flex } from '@derbysoft/neat-design';
import DotStatus from '../../components/DotStatus';

export interface ViewVoiceProps {
  open: boolean;
  invoiceId?: string;
  imageUrl?: string;
  onClose?: () => void;
}

const defaultInvoiceImage = (invoiceId = 'INVOICE') => {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1000" viewBox="0 0 1200 1000">
      <rect width="1200" height="1000" fill="#f5f7fb"/>
      <rect x="60" y="60" width="1080" height="880" rx="24" fill="#ffffff" stroke="#e5e7eb"/>
      <rect x="100" y="100" width="180" height="48" rx="8" fill="#eef2ff"/>
      <text x="130" y="133" font-size="30" font-family="Arial, sans-serif" fill="#4f46e5" font-weight="700">Invoice</text>
      <text x="820" y="130" font-size="28" font-family="Arial, sans-serif" fill="#6b7280" font-weight="600">INVOICE</text>
      <text x="100" y="240" font-size="36" font-family="Arial, sans-serif" fill="#111827" font-weight="700">DerbySoft</text>
      <text x="100" y="290" font-size="22" font-family="Arial, sans-serif" fill="#374151">Business Unit: Connectivity Services</text>
      <text x="100" y="330" font-size="22" font-family="Arial, sans-serif" fill="#374151">Address: 6th Floor, Building B No. 120, Lane 91, E&apos; Shan Road</text>
      <text x="100" y="370" font-size="22" font-family="Arial, sans-serif" fill="#374151">Shanghai 200127, China</text>

      <rect x="100" y="440" width="480" height="220" rx="12" fill="#f8fafc" stroke="#e2e8f0"/>
      <text x="130" y="490" font-size="22" font-family="Arial, sans-serif" fill="#64748b">Bill To</text>
      <text x="130" y="535" font-size="26" font-family="Arial, sans-serif" fill="#0f172a" font-weight="700">${invoiceId}</text>
      <text x="130" y="575" font-size="20" font-family="Arial, sans-serif" fill="#475569">Customer Name: Demo Company</text>
      <text x="130" y="610" font-size="20" font-family="Arial, sans-serif" fill="#475569">Address: 123 Example Road</text>

      <rect x="620" y="440" width="470" height="220" rx="12" fill="#f8fafc" stroke="#e2e8f0"/>
      <text x="650" y="490" font-size="22" font-family="Arial, sans-serif" fill="#64748b">Invoice Details</text>
      <text x="650" y="535" font-size="20" font-family="Arial, sans-serif" fill="#475569">Invoice No.: ${invoiceId}</text>
      <text x="650" y="575" font-size="20" font-family="Arial, sans-serif" fill="#475569">Issue Date: 2026/06/05</text>
      <text x="650" y="610" font-size="20" font-family="Arial, sans-serif" fill="#475569">Due Date: 2026/07/05</text>
      <text x="650" y="645" font-size="20" font-family="Arial, sans-serif" fill="#475569">Payment Terms: 30 days</text>

      <rect x="100" y="700" width="980" height="160" rx="12" fill="#f8fafc" stroke="#e2e8f0"/>
      <text x="150" y="760" font-size="26" font-family="Arial, sans-serif" fill="#0f172a" font-weight="700">Total amount due</text>
      <text x="930" y="760" font-size="34" font-family="Arial, sans-serif" fill="#111827" font-weight="700">CNY 92.09</text>
      <line x1="150" y1="790" x2="1050" y2="790" stroke="#dbe2ea" stroke-width="2"/>
      <text x="150" y="830" font-size="18" font-family="Arial, sans-serif" fill="#64748b">Generated by AR Statements</text>
      <text x="930" y="830" font-size="18" font-family="Arial, sans-serif" fill="#64748b">Invoice preview</text>
    </svg>
  `;

  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
};

const ViewVoice: React.FC<ViewVoiceProps> = ({
  open,
  invoiceId = '1U7R9P3S',
  imageUrl,
  onClose,
}) => {
  const src = imageUrl || defaultInvoiceImage(invoiceId);

  return (
    <Drawer
      open={open}
      onClose={onClose}
      title={
        <Flex align="center" gap={8} justify="space-between">
          <span>发票ID：{invoiceId}</span>
          <DotStatus text="已开票待确认" style={{ fontSize: 16 }} />
        </Flex>
      }
      width={960}
      placement="right"
      destroyOnHidden
      className="invoice-drawer"
      footer={
        <div className="invoice-drawer__footer">
          <Button type="tertiary">下载发票</Button>
          <Button>重新上传发票</Button>
        </div>
      }
    >
      <div className="invoice-drawer__content">
        <img
          className="invoice-drawer__image"
          src={src}
          alt={`Invoice ${invoiceId}`}
        />
      </div>
    </Drawer>
  );
};

export default ViewVoice;
