import { menus } from './config.menu';

const getRoutes = (items) => {
  const result = [];

  items.reduce((acc, item) => {
    if (item.children) {
      acc.push(...getRoutes(item.children));
    } else {
      acc.push({
        rotue: item.route,
        permissions: item.permissions,
      });
    }
    return acc;
  }, result);

  return result;
};

/**
 * Retrieves and returns the application routes based on the provided menu configuration.
 *
 * @remarks
 * This module exports the result of processing menu items into route configurations.
 * The routes are generated by transforming the menu structure using the `getRoutes` function.
 *
 * @returns The generated route configuration derived from the menu structure
 */
export default getRoutes(menus);
